#!/bin/bash
set -euo pipefail

# generate-compose-override.sh
# Generates docker-compose.override.yml dynamically based on .env

OVERRIDE_FILE="docker-compose.override.yml"
ENV_FILE="${1:-.env}"

# Load .env if it exists
if [[ -f "$ENV_FILE" ]]; then
    set -a
    source "$ENV_FILE"
    set +a
fi

# Remove existing override file
rm -f "$OVERRIDE_FILE"

# Check if SCAN_PATH_2 is set and non-empty
if [[ -n "${SCAN_PATH_2:-}" ]]; then
    echo "✓ SCAN_PATH_2 is set: $SCAN_PATH_2"
    echo "  Generating override with second volume mount..."
    
    cat > "$OVERRIDE_FILE" << EOF
# Auto-generated by generate-compose-override.sh
# DO NOT EDIT MANUALLY - This file is regenerated on each build
# Generated at: $(date)

services:
  storage-sage-daemon:
    volumes:
      - ${SCAN_PATH_2}:/mnt/scan2:ro
EOF

    echo "✓ Created $OVERRIDE_FILE with SCAN_PATH_2 mount"
else
    echo "ℹ SCAN_PATH_2 not set - skipping secondary volume mount"
    
    # Create empty override file (prevents docker-compose warnings)
    cat > "$OVERRIDE_FILE" << EOF
# Auto-generated by generate-compose-override.sh
# SCAN_PATH_2 not configured - no additional volumes
# Generated at: $(date)

services: {}
EOF
    
    echo "✓ Created empty $OVERRIDE_FILE"
fi